Init CI for Pull Requests
NoranPeLage/match-and-watch pull request #1
Opened 2020-11-08 18:26 UTC by NoranPeLage

2020-11-08 18:31 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@bycedric/use-expo?release-channel=pr-1).

2020-11-08 18:32 UTC, ThomasCarca commented on .github/workflows/pr.yml
> +      - run: expo publish --release-channel=pr-${{ github.event.number }}
Maybe having a branch name in the release channel name would be a good idea ?

2020-11-08 18:35 UTC, ThomasCarca requested changes

2020-11-08 18:35 UTC, ThomasCarca commented on .github/workflows/pr.yml
> +      - run: expo publish --release-channel=pr-${{ github.event.number }}
Maybe having a branch name in the release channel name would be a good idea ?

2020-11-08 18:37 UTC, ThomasCarca commented on .github/workflows/pr.yml
> +      - run: expo publish --release-channel=pr-${{ github.event.number }}
Maybe having a branch name in the release channel name would be a good idea ?

2020-11-08 18:38 UTC, ThomasCarca requested changes

2020-11-08 18:38 UTC, ThomasCarca commented on .github/workflows/pr.yml
> +          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
azd

2020-11-08 19:01 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-09 08:33 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-11 17:27 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-11 17:36 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-${GITHUB_REF##*/}).

2020-11-11 17:41 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-).

2020-11-11 17:55 UTC, tfonroques approved these changes, later dismissed

2020-11-11 17:56 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-11 17:57 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-11 17:59 UTC, NoranPeLage commented
App is ready for review, you can [see it here](https://expo.io/@noranpelage/match-and-watch?release-channel=pr-1).

2020-11-11 18:04 UTC, ThomasCarca submitted a review, later dismissed

2020-11-11 18:13 UTC, ThomasCarca approved these changes

2020-11-11 18:13 UTC, tfonroques approved these changes

2020-11-11 18:14 UTC, merged